### ISSUE TITLE
keyboard augment destroys dictionary-like entity annotations

### ISSUE THREAD

**Issue by ka-bu** [RasaHQ/taipo#33]
Dictionary-like entity annotations as described [here](https://rasa.com/docs/rasa/nlu-training-data/#entities-roles-and-groups) will result in `taipo keyboard augment` output malformed annotations that Rasa can't identify.

E.g. `python -m taipo keyboard augment example.yml out.yml` with `example.yml` containing:
```yaml
version: "2.0"
nlu:
- intent: intent
  examples: |
    - this will [fail]{"entity" : problem}
 ```

Will result in:
```yaml
version: '2.0'
nlu:
- intent: intent
  examples: |
   - 'tgie wjlp [fail] {" dntitt ": problem }'
```
... where there is a space between the ] and { which causes problems later.
