### ISSUE TITLE
`taipo transliterate` maps numbers to entity strings

### ISSUE THREAD

**Issue by ka-bu** [RasaHQ/taipo#34]
Because of how `taipo transliterate` tries to mask entities (i.e. by replacing them to indices before transliteration, and then mapping them back after transliteration), what can happen is that...
```yaml
version: "2.0"
nlu:
- intent: intent
  examples: |
    - What does this [strange](entity_name) error mean?
    - transliterate will do 0 things here
```
is turned into 
```yaml
version: '2.0'
nlu:
- intent: intent
  examples: |
   - Wհատ դօես թիս [ստրանգե](entity_name) երրօր մեան?
   - տրանսլիտերատե wիլլ դօ entity_name թինգս հերե
```
... note the "entity_name" where the "0" used to be.
